### ISSUE TITLE
Remove non-updated items

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#1067]
```yml
          - item:
            name: Yipee
            homepage_url: 'https://yipee.io/'
            logo: yipeeio.svg
            twitter: 'https://twitter.com/yipeeioca'
            crunchbase: 'https://www.crunchbase.com/organization/yipee-io'
          - item:
            name: MidoNet
            homepage_url: 'https://www.midonet.org/'
            repo_url: 'https://github.com/midonet/midonet'
            logo: midonet.svg
            twitter: 'https://twitter.com/midokura'
            crunchbase: 'https://www.crunchbase.com/organization/midokura'
```
