### ISSUE TITLE
Cloud Native Artificial Intelligence Sublandscape

### ISSUE THREAD

**Issue by ronaldpetty** [cncf/landscape#3793]
Aloha.

The cool folks over at #wg-artifical-intelligence are creating a sublandscape similar to WASM #2387 .

* I see we are to edit the landscape.yml (which we started). While playing around with the Rust tool, I see to create a "see-only" view requires changing settings.yml. Is that something we need to do as well or will that be handled by someone else?
* We are light on logos; is there a preferred method to deal with that issue?
* How much of the sublandscape must be completed before it can be included? I feel it will be a looooooong time to get the bulk finished; but might be nice to get a subset done? Any comments appreciated. 
* Is there a staging area (so we can piecemeal and check? (Thinking of crunch base or things that might break that I haven't tried)

This image was from my laptop based on editing others (in the CNCF AI WG) work.

<img width="973" alt="image" src="https://github.com/cncf/landscape/assets/1390435/ed3c9309-6877-41f0-84ce-9dd4e0a5ca6f">

**Comment by ronaldpetty** [comment]
[cnai-sublandscape-draft.zip](https://github.com/cncf/landscape/files/14552488/cnai-sublandscape-draft.zip)

This zip has the inflight data.yml (aka landscape.yml) and logos directory for the very few that I have found so far. There are a few more logos out there but they are PNG and need to be converted.

**Comment by panpan0000** [comment]
Hi, Ron, as we talk, can you please add one more missing item (essential for GPU efficiency and multi-tenancy platform )
```
  - category:
    name: CNAI
    subcategories:
    - subcategory:
      name: General Orchestration
      items:
        - item:
          name: HAMi
          description: Heterogeneous AI Computing Virtualization(vGPU)
          homepage_url: https://github.com/Project-HAMi/HAMi
          repo_url: https://github.com/Project-HAMi/HAMi
          logo:
          crunchbase:
          unnamed_organization: true     
```
