### ISSUE TITLE
Project/product removal

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#462]
As per our [policy](https://github.com/cncf/landscape#non-updated-items), I'm removing projects with a last commit older than 3 months and products with a last tweet older than 3 months. I'm pasting the removed YAML here, and any of these projects/products are welcome to get re-added to the landscape if they revive. However, only showing active items is an explicit goal of the landscape.

For open source, the filter is: https://landscape.cncf.io/grouping=no&license=open-source&sort=latest-commit
For closed source, it is: https://landscape.cncf.io/grouping=no&license=not-open-source&sort=latest-tweet

Other notes: Zabbix uses SVN, which is fine, but they have not (yet) been willing to create a functional mirror to GitHub: https://support.zabbix.com/browse/ZBXNEXT-4162

```yml
          - item:
            name: Zabbix
            homepage_url: 'https://www.zabbix.com/'
            repo_url: 'https://github.com/zabbix/zabbix'
            branch: trunk
            logo: 'https://www.enov8.com/wp-content/uploads/2017/02/zabbix_logo.svg'
            twitter: 'https://twitter.com/zabbix'
            crunchbase: 'https://www.crunchbase.com/organization/zabbix'
          - item:
            name: KappaIO
            homepage_url: 'http://kappa.readthedocs.io/en/develop/'
            repo_url: 'https://github.com/garnaat/kappa'
            logo: ./hosted_logos/kappaio.svg
            crunchbase: 'https://www.crunchbase.com/organization/kappaio'
          - item:
            name: Dawson
            homepage_url: 'https://github.com/dawson-org'
            repo_url: 'https://github.com/dawson-org/dawson-cli'
            logo: ./hosted_logos/dawson.svg
            crunchbase: 'https://www.crunchbase.com/organization/dawson-c553'
          - item:
            name: LambCI
            homepage_url: 'http://lambci.org/'
            repo_url: 'https://github.com/lambci/lambci'
            logo: ./hosted_logos/lambci.svg
            twitter: 'https://twitter.com/lamb_ci'
            crunchbase: 'https://www.crunchbase.com/organization/lambci'
          - item:
            name: Infinit
            homepage_url: 'https://www.infinit.sh/'
            repo_url: 'https://github.com/infinit/elle'
            logo: ./hosted_logos/infinit.svg
            twitter: 'https://twitter.com/infinit_sh'
            crunchbase: 'https://www.crunchbase.com/organization/infinit'
          - item:
            name: VMware Haret
            homepage_url: 'https://github.com/vmware/haret'
            stock_ticker: VMW
            repo_url: 'https://github.com/vmware/haret'
            logo: ./hosted_logos/vmware-haret.svg
            twitter: 'https://twitter.com/VMware'
            crunchbase: 'https://www.crunchbase.com/organization/vmware'
          - item:
            name: Mitoc Group Deep
            homepage_url: 'https://docs.deep.mg/'
            repo_url: 'https://github.com/MitocGroup/deep-framework'
            logo: 'https://www.mitocgroup.com/images/logos/mitoc.svg'
            twitter: 'https://twitter.com/MitocGroup'
            crunchbase: 'https://www.crunchbase.com/organization/mitoc-group-inc'
          - item:
            name: Empire
            homepage_url: 'http://engineering.remind.com/'
            repo_url: 'https://github.com/remind101/empire'
            logo: 'http://toddeichel.com/images/logos/remind.svg'
            twitter: 'https://twitter.com/remindeng'
            crunchbase: 'https://www.crunchbase.com/organization/remind'
          - item:
            name: Funktion
            homepage_url: 'https://funktion.fabric8.io/'
            repo_url: 'https://github.com/funktionio/funktion'
            logo: ./hosted_logos/funktion.svg
            twitter: 'https://twitter.com/funktionio'
            crunchbase: 'https://www.crunchbase.com/organization/funktion'
          - item:
            name: Gordon
            homepage_url: 'http://jorgebastida.com/'
            repo_url: 'https://github.com/jorgebastida/gordon'
            logo: 'https://gordon.readthedocs.io/en/latest/_static/logo_text.svg'
            twitter: 'https://twitter.com/jorgebastida'
            crunchbase: 'https://www.crunchbase.com/organization/gordon'
          - item:
            name: Microcule
            homepage_url: 'https://github.com/Stackvana'
            repo_url: 'https://github.com/Stackvana/microcule'
            logo: ./hosted_logos/stackvana.svg
            crunchbase: 'https://www.crunchbase.com/organization/stackvana'
          - item:
            name: Meros
            homepage_url: 'https://meros.io/'
            logo: ./hosted_logos/meros.svg
            twitter: 'https://twitter.com/merosdevops'
            crunchbase: 'https://www.crunchbase.com/organization/meros-inc'
          - item:
            name: OpsClarity
            homepage_url: 'https://www.opsclarity.com/'
            logo: ./hosted_logos/opsclarity.svg
            twitter: 'https://twitter.com/opsclarity'
            crunchbase: 'https://www.crunchbase.com/organization/opsclarity'
          - item:
            name: Convox
            homepage_url: 'https://convox.com/'
            rep_url: 'https://github.com/convox'
            logo: ./hosted_logos/convox.svg
            twitter: 'https://twitter.com/goconvox'
            crunchbase: 'https://www.crunchbase.com/organization/convox'
          - item:
            name: SnapRoute
            homepage_url: 'https://snaproute.com/'
            logo: ./hosted_logos/snaproute.svg
            twitter: 'https://twitter.com/snaproute'
            crunchbase: 'https://www.crunchbase.com/organization/snaproute'
          - item:
            name: OpBeat
            homepage_url: 'https://opbeat.com/'
            logo: 'https://crunchbase-production-res.cloudinary.com/image/upload/v1408666566/nwh15vkpdfklojbp70bo.png'
            twitter: 'https://twitter.com/opbeat'
            crunchbase: 'https://www.crunchbase.com/organization/opbeat'
          - item:
            name: Springpath
            homepage_url: 'http://springpathinc.com/'
            logo: ./hosted_logos/springpath.svg
            twitter: 'https://twitter.com/springpathinc'
            crunchbase: 'https://www.crunchbase.com/organization/springpath-inc'
          - item:
            name: Axibase
            homepage_url: 'https://axibase.com/'
            logo: ./hosted_logos/axibase.svg
            twitter: 'https://twitter.com/axibase'
            crunchbase: 'https://www.crunchbase.com/organization/axibase'
          - item:
            name: Rocana
            homepage_url: 'https://www.rocana.com/'
            logo: ./hosted_logos/rocana.svg
            twitter: 'https://twitter.com/rocanainc'
            crunchbase: 'https://www.crunchbase.com/organization/rocana'
          - item:
            name: Solano Labs
            homepage_url: 'https://www.solanolabs.com/'
            logo: ./hosted_logos/solanolabs.svg
            twitter: 'https://twitter.com/SolanoLabs'
            crunchbase: 'https://www.crunchbase.com/organization/solano-labs'
          - item:
            name: Apcera
            homepage_url: 'https://www.apcera.com/'
            logo: ./hosted_logos/apcera.svg
            twitter: 'https://twitter.com/apcera'
            crunchbase: 'https://www.crunchbase.com/organization/ericsson'
          - item:
            name: Distelli
            homepage_url: 'https://www.distelli.com/'
            logo: 'https://crunchbase-production-res.cloudinary.com/image/upload/fknsopnhqyctio2vqpuh.png'
            twitter: 'https://twitter.com/distelli'
            crunchbase: 'https://www.crunchbase.com/organization/distelli-inc'
          - item:
            name: Webtask
            homepage_url: 'https://webtask.io/'
            logo: 'https://cdn.auth0.com/website/assets/pages/press/img/resources/webtask-logo-f479cae0f6.svg'
            twitter: 'https://twitter.com/webtaskio'
            crunchbase: 'https://www.crunchbase.com/organization/webtask'
          - item:
            name: Clouber
            homepage_url: 'https://www.clouber.io/'
            logo: 'https://s3.amazonaws.com/awsmp-logos/clouber.PNG'
            twitter: 'https://twitter.com/clouberio'
            crunchbase: 'https://www.crunchbase.com/organization/clouber'
          - item:
            name: OVH Functions
            homepage_url: 'https://labs.ovh.com/ovh-functions'
            logo: 'https://www.i2coalition.com/wp-content/uploads/2017/09/logo-ovh-us-horizontal-blue.png'
            twitter: 'https://twitter.com/ovh_labs'
            crunchbase: 'https://www.crunchbase.com/organization/ovh-com'

```
