### ISSUE TITLE
`yarn fetch` is conflating 2 images

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#512]
These two entries are point to different images:
```yml
          - item:
            name: Codefresh
            homepage_url: 'https://codefresh.io/'
            logo: ./hosted_logos/codefresh.svg
            twitter: 'https://twitter.com/codefresh'
            crunchbase: 'https://www.crunchbase.com/organization/code-fresh'
          - item:
            name: Codefresh Registry
            homepage_url: 'https://codefresh.io/docs/docs/docker-registries/codefresh-registry/'
            logo: 'https://codefresh.io/wp-content/uploads/2018/03/Codefresh-Registry.svg'
            crunchbase: 'https://www.crunchbase.com/organization/code-fresh'
```
But `yarn fetch` is having both of them served by https://landscape.cncf.io/logos/codefresh-registry.svg.
