### ISSUE TITLE
Removed items

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#716]
As described in https://github.com/cncf/landscape/blob/master/README.md#non-updated-items we're removing the following items:
```yml
          - item:
            name: Mantl
            homepage_url: 'https://mantl.io/'
            repo_url: 'https://github.com/mantl/mantl'
            logo: ./hosted_logos/mantl.svg
            twitter: 'https://twitter.com/usemantl'
            crunchbase: 'https://www.crunchbase.com/organization/mantl-9966'
          - item:
            name: BuddyBuild
            homepage_url: 'https://www.buddybuild.com/'
            logo: 'https://docs.buddybuild.com/gitbook/gitbook-plugin-buddybuild/logo-bb.svg'
            twitter: 'https://twitter.com/buddybuild'
            crunchbase: 'https://www.crunchbase.com/organization/buddybuild'
          - item:
            name: goPaddle
            description: Developer Friendly DevOps platform for Kubernetes Deployments
            homepage_url: 'https://www.gopaddle.io/#/'
            logo: ./hosted_logos/gopaddle.svg
            crunchbase: 'https://www.crunchbase.com/organization/bluemeric'
          - item:
            name: Syncano
            homepage_url: 'https://syncano.io/'
            logo: ./hosted_logos/syncano.svg
            twitter: 'https://twitter.com/Syncano'
            crunchbase: 'https://www.crunchbase.com/organization/syncano'
```
