### ISSUE TITLE
Removing un-updated items

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#807]
Following our policy, we're removing all items older than 3 months:

```yml
          - item:
            name: RunV
            homepage_url: 'https://github.com/hyperhq/runv'
            repo_url: 'https://github.com/hyperhq/runv'
            logo: ./hosted_logos/runv.svg
            crunchbase: 'https://www.crunchbase.com/organization/hyper-4'
          - item:
            name: Intel Clear Containers
            homepage_url: 'https://clearlinux.org/containers'
            repo_url: 'https://github.com/clearcontainers/runtime'
            logo: ./hosted_logos/intel-clearcontainers.svg
            twitter: 'https://twitter.com/clearlinux'
            crunchbase: 'https://www.crunchbase.com/organization/intel'
          - item:
            name: LeoFS
            homepage_url: 'https://leo-project.net/leofs/'
            repo_url: 'https://github.com/leo-project/leofs'
            logo: ./hosted_logos/leofs.svg
            twitter: 'https://twitter.com/LeoFastStorage'
            crunchbase: 'https://www.crunchbase.com/organization/leo-project'
          - item:
            name: Netflix Ribbon
            homepage_url: 'https://github.com/Netflix/ribbon'
            repo_url: 'https://github.com/Netflix/ribbon'
            logo: ./hosted_logos/netflix-ribbon.svg
            twitter: 'https://twitter.com/netflixoss'
            crunchbase: 'https://www.crunchbase.com/organization/netflix'
          - item:
            name: Shep
            homepage_url: 'https://www.bustle.com/labs'
            repo_url: 'https://github.com/bustle/shep'
            logo: ./hosted_logos/shep.svg
            twitter: 'https://twitter.com/bustle'
            crunchbase: 'https://www.crunchbase.com/organization/bustle'
          - item:
            name: ContainerPilot
            homepage_url: 'https://www.joyent.com/containerpilot'
            repo_url: 'https://github.com/joyent/containerpilot'
            logo: ./hosted_logos/containerpilot.svg
            twitter: 'https://twitter.com/joyent'
            crunchbase: 'https://www.crunchbase.com/organization/joyent'
          - item:
            name: Hystrix
            homepage_url: 'https://github.com/Netflix/Hystrix'
            repo_url: 'https://github.com/Netflix/Hystrix'
            logo: ./hosted_logos/hystrix.svg
            twitter: 'https://twitter.com/netflixoss'
            crunchbase: 'https://www.crunchbase.com/organization/netflix'
          - item:
            name: OpenLambda
            homepage_url: 'https://open-lambda.org/'
            repo_url: 'https://github.com/open-lambda/open-lambda'
            logo: ./hosted_logos/openlambda.svg
            crunchbase: 'https://www.crunchbase.com/organization/openlambda'
          - item:
            name: SmartStack
            homepage_url: 'https://medium.com/airbnb-engineering/smartstack-service-discovery-in-the-cloud-4b8a080de619'
            repo_url: 'https://github.com/airbnb/synapse'
            logo: ./hosted_logos/smartstack.svg
            twitter: 'https://twitter.com/AirbnbEng'
            crunchbase: 'https://www.crunchbase.com/organization/airbnb'

```

**Comment by dankohn** [comment]
And Netsil stopped tweeting after being acquired by Nutanix.
```yml
          - item:
            name: Netsil
            homepage_url: 'https://netsil.com/'
            logo: ./hosted_logos/netsil.svg
            twitter: 'https://twitter.com/Netsil_HQ'
            crunchbase: 'https://www.crunchbase.com/organization/nutanix'
```
