### ISSUE TITLE
Fatal error for malformed Twitter

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#936]
This entry:
```yml
          - item:
            name: Cumulus
            homepage_url: 'https://cumulusnetworks.com'
            logo: ./hosted_logos/cumulus.svg
            twitter: 'https://twitter.com/CumulusNetworks/'
            crunchbase: 'https://www.crunchbase.com/organization/cumulus-networks'
```
produced this odd result (tweets show but see the `@` Twitter entry and last updated date is off):
<img width="913" alt="screen shot 2018-10-27 at 11 14 03 pm" src="https://user-images.githubusercontent.com/3083270/47611556-61e49d00-da3e-11e8-912f-050f00babbd2.png">

Closing `/` in Twitter, GitHub, or Crunchbase should be a fatal error.
