### ISSUE TITLE
Non-updated projects

### ISSUE THREAD

**Issue by dankohn** [cncf/landscape#940]
Removing non-updated projects and products, as described in https://github.com/cncf/landscape#non-updated-items :

 ```yaml
          - item:
            name: Clay
            homepage_url: 'https://www.clay.run/'
            logo: ./hosted_logos/clay.svg
            twitter: 'https://twitter.com/runclay'
            crunchbase: 'https://www.crunchbase.com/organization/clay-labs'
          - item:
            name: Nano Lambda
            homepage_url: 'https://nano-lambda.com/'
            logo: ./hosted_logos/nanolambda.svg
            crunchbase: 'https://www.crunchbase.com/organization/nano-lambda'
          - item:
            name: Weblab
            homepage_url: 'https://weblab.io/'
            logo: ./hosted_logos/weblab.svg
            crunchbase: 'https://www.crunchbase.com/organization/weblab'
          - item:
            name: Apache Apex
            homepage_url: 'https://apex.apache.org/'
            repo_url: 'https://github.com/apache/apex-core'
            logo: ./hosted_logos/apache-apex.svg
            twitter: 'https://twitter.com/apacheapex'
            crunchbase: 'https://www.crunchbase.com/organization/apache'
          - item:
            name: DEEP Framework
            homepage_url: 'https://www.mitocgroup.com/partners/aws/'
            repo_url: 'https://github.com/MitocGroup/deep-framework'
            logo: 'https://raw.githubusercontent.com/MitocGroup/deep-framework/master/docs/logo.svg'
            crunchbase: 'https://www.crunchbase.com/organization/mitoc-group-inc'
          - item:
            name: LizardFS
            homepage_url: 'https://lizardfs.com/'
            repo_url: 'https://github.com/lizardfs/lizardfs'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/LizardFS_Logo.svg'
            twitter: 'https://twitter.com/LizardFS'
            crunchbase: 'https://www.crunchbase.com/organization/lizardfs-inc'
          - item:
            name: Sheepdog
            homepage_url: 'https://sheepdog.github.io/sheepdog/'
            repo_url: 'https://github.com/sheepdog/sheepdog'
            logo: ./hosted_logos/sheepdog.svg
            crunchbase: 'https://www.crunchbase.com/organization/sheepdog'
          - item:
            name: Snap
            homepage_url: 'https://github.com/intelsdi-x/snap'
            repo_url: 'https://github.com/intelsdi-x/snap'
            logo: ./hosted_logos/snap.svg
            twitter: 'https://twitter.com/IntelSoftware'
            crunchbase: 'https://www.crunchbase.com/organization/intel'
```
